api_key: "EMPTY"
api_base: "http://127.0.0.1:12345/v1"
temperature: 0.1
#tools_folder: "/root/gzc/StableToolBench/rawdata/data/toolenv/tools"
tools_folder: "/home/t653z659/StableToolBench/toolenv/toolenv2404_filtered"
port: 12001
#model: simulation-250123-qwen25-mixed
model: "mirrorapi"   # 这里跟上面保持一致